spring.application.name=DeliveySystem-WebFlux

# ===================================================================
# Security Configuration
# ===================================================================
# Dynamically pulls your IP from your .env file via docker-compose!
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_BASE_URL}/realms/delivery-realm

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_BASE_URL:http://localhost:9090}/realms/delivery-realm

# ===================================================================
# Reactive MongoDB Configuration
# ===================================================================
# Reaching across the Docker network to the Mongo container
#spring.data.mongodb.uri=mongodb://delivery-mongo:27017/delivery_db
#
## ===================================================================
## Reactive Redis Configuration
## ===================================================================
## Reaching across the Docker network to the Redis container
#spring.data.redis.host=delivery-redis
#spring.data.redis.port=6379

spring.data.mongodb.uri=mongodb://${MONGO_HOST:localhost}:27018/delivery_db
spring.data.redis.host=${REDIS_HOST:localhost}

management.endpoints.web.exposure.include=health

app.delivery.fee-per-km=500.0
