spring.application.name=DeliveySystem-WebFlux
spring.data.mongodb.uri=mongodb://delivery-mongo:27017/delivery_db
spring.data.redis.host=delivery-redis
spring.data.redis.port=6379
management.endpoints.web.exposure.include=health
app.delivery.fee-per-km=500.0

